Update README.md
jbusecke/cookiecutter-science-project pull request #2
Opened 2019-10-22 17:42 UTC by dhruvbalwada

2019-10-24 20:30 UTC, jbusecke requested changes
Great additions. Thanks @dhruvbalwada.

2019-10-24 20:30 UTC, jbusecke commented on README.md
> +Contents of the data folder should not be committed to the github repository (*the data folder can be included to the .gitignore file - scroll the bottom of the .gitignore in the template*) . Ideally
You should probably change "I" to we, since you will be a contributor now!

2019-10-24 20:30 UTC, jbusecke commented on README.md
> +
Good point!

2019-11-18 23:50 UTC, dhruvbalwada reviewed
Fixed.

2019-11-19 15:47 UTC, jbusecke commented
Could you remind me what was fixed?

2019-11-19 17:41 UTC, dhruvbalwada commented
Ugh did I kill the history of this conversation... haha. 
Umm some language - you wanted me to change "I" to "we" in one part.

2019-11-19 19:03 UTC, jbusecke approved these changes
Looks great. Thanks for putting together the PR

2019-11-19 19:03 UTC, merged