Fixed readthedocs error
jbusecke/cookiecutter-science-project pull request #36
Opened 2021-04-02 12:51 UTC by lukegre

Readthedocs couldn't import the package, so versioning and API docs couldn't be built. 

Changed `.readthedocs.yaml` so that setuptools installs from `.` instead of `package`

2021-04-02 12:53 UTC, lukegre commented
This is a really great template BTW!

2021-04-07 12:29 UTC, jbusecke commented
Hey @lukegre thanks for checking this out.

Before merging I would like to understand more why this was failing. Is there a change to rtd that makes this necessary?

2021-04-07 19:23 UTC, lukegre commented
My understanding is that setuptools is able to install the package from `setup.py` in the package root directory (`.`). The path `package` doesn't contain a `setup.py` file. 

There might be something else that I'm not getting, but changing this for me made my doc building pass on readthedocs.org.

2021-04-10 18:15 UTC, jbusecke requested changes
I dug more into this over at https://github.com/jbusecke/cmip6_preprocessing/pull/113

I learned a few things: 

1. You have to force the newest version [v2](https://docs.readthedocs.io/en/stable/config-file/v2.html#conda) in the config file.
2. Over in that PR I also migrated all my dependencies to a pip only workflow, because the build time was getting absurd. 

Over all I think we should switch the install [method](https://docs.readthedocs.io/en/stable/config-file/v2.html#packages) to `pip`(the default) from `setuptools` in this PR.

Unsure if we should also do the complete switch to pip for the docs for the template...But that could be addressed in a new PR.

2021-04-19 08:39 UTC, lukegre commented
I was going to say I'm all for pip but after looking at the `cmip_preprocessing` RTD troubles I'm having second thoughts. There might be issues if more complex packages are required?

2021-06-26 00:33 UTC, jbusecke approved these changes

2021-06-26 00:33 UTC, jbusecke commented
It took me like a month to figure out this crap over at https://github.com/jbusecke/cmip6_preprocessing/pull/115, but you were absolutely right. Thanks again @lukegre

2021-06-26 00:33 UTC, merged